### ISSUE TITLE
Should work with Blue ROMs unaltered

### ISSUE THREAD

**Issue by JoaoMSerra** [jakefordyce/PokemonROMEditor#1]
Is there any reason for the program to not officially support Pokémon Blue ROMs with the current codebase? It appears that Pokémon Blue works properly with this program. Should the documentation be updated?

Even Yellow should work properly, but I haven't tested it yet.

**Comment by jakefordyce** [comment]
Hey, sorry for the super delayed response. I just saw this issue and the pull request this week and have been really busy. 

I think you are correct that it *should* work with Pokemon Blue. I will try it out and update the documentation.

I'm less confident in it supporting yellow since I think there are some differences in the code and the way this program works is very dependent on pointers/data being in exact locations. I'll try that out also though and see.

**Comment by jakefordyce** [comment]
Confirmed that it does at least open the Pokemon Blue ROM correctly. Since it is able to find all of the data I'm assuming it should also be able to save changes to the blue rom. I will update the readme to include blue version.

I did also try out the Yellow version and confirmed the program does not in its current state support Yellow version.
